### PR TITLE
Update App.desktop.vue

### PR DESCRIPTION
**Pull request by edencorbin**
I was having issues running this app with logging out and then still being able to access protected pages. I could be missing something, but it seems the token stored in localStorage is not removed and this causes the problem. This minor update/inclusion appears to fix it on my end.

### CODE REVIEW

**Comment by ndabAP** [comment]
Hey @edencorbin thanks for your pull request.

There is definitely a bug with that. But it comes from the logout method, which seems to delete cookie occasionally, which is strange. Repeat the process frequently and you will notice it will work some time.

I welcome your pull request but the protected page validation checks only for a cookie, see 

> frontend/src/bootstrap.desktop.js:32-34

But clearing the local storage as you committed has to be done when logging out either way :) So, you have two possibilities:

1. Investigate the problem you reported and commit the success
2. remove the final semicolon (because the project uses [Standard](https://github.com/standard/standard)) and I merge it.

**Comment by ndabAP** [comment]
**Update**: It seems that I'm wrong. I can't delete the cookie anymore even after several tries.

**Comment by ndabAP** [comment]
I figured it out. One have to replace the `deleteCookie` method with this:

```js
deleteCookie (cookie) {
  document.cookie = `${cookie}=; expires=Thu, 01 Jan 1970 00:00:01 GMT;`
}
```

**Comment by edencorbin** [comment]
Made both those changes, thanks for looking into this.

**Pull request merged**
